volumes:
  wp:

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - /home/jmougel/Documents/inception/srcs/.env
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge