services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - /home/jmougel/Documents/inception/srcs/.env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    networks:
      - docker-network
    restart: on-failure
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - /home/jmougel/Documents/inception/srcs/.env
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    networks:
      - docker-network
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - /home/jmougel/Documents/inception/srcs/.env
    environment:
      - WORDPRESS_DB_HOST=${MARIADB_HOST}
      - WORDPRESS_DB_NAME=${MARIADB_NAME}
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_USER_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    expose:
      - 9000
    networks:
      - docker-network
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jmougel/data/wp
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jmougel/data/db

networks:
  docker-network:
    driver: bridge