[DEFAULT]
bantime = 10m
findtime = 10m
maxretry = 5
backend = polling
protocol = tcp
chain = INPUT
banaction = iptables-multiport
action_ = %(banaction)s[port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action = %(action_)s

[vsftpd]
enabled = true
port = ftp,ftp-data,ftps,ftps-data
filter = vsftpd
logpath = /var/log/vsftpd/vsftpd.log
